require("plugins.blink")()
require("plugins.catppuccin")()
require("plugins.cloak")()
require("plugins.conform")()
require("plugins.dadbod")()
-- require("plugins.fff")()
require("plugins.fugitive")()
require("plugins.harpoon")()
require("plugins.hlsearch")()
require("plugins.lsp")()
require("plugins.lualine")()
require("plugins.luasnip")()
require("plugins.obsidian")()
require("plugins.oil")()
-- require("plugins.opencode")()
require("plugins.render-markdown")()
require("plugins.statusline")()
require("plugins.surround")()
require("plugins.telescope")()
require("plugins.treesitter")()
require("plugins.undotree")()
